run:
  # default concurrency is a available CPU number
  concurrency: 4
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 3m
  tests: true

linters:
  disable:
    - exhaustivestruct

linters-settings:
  lll:
    line-length: 160
  funlen:
    lines: 110
    statements: 60